"""pyhandlexl — read and write Excel .xlsx worksheets as organised, labelled tables."""

from pyhandlexl import grid
from pyhandlexl._merge import MergeReport
from pyhandlexl.column_type import ColumnType
from pyhandlexl.core import (
    append_rows,
    clear_all_sheet_data,
    create_csv,
    create_sheet,
    create_workbook,
    delete_sheet,
    delete_table,
    delete_workbook,
    export_xl_to_csv,
    import_csv_to_xl,
    list_sheets,
    list_tables,
    read_sheet,
    rename_sheet,
    sheet_exists,
    sheet_kind,
    table_info,
    write_sheet,
)
from pyhandlexl.errors import (
    CellTypeError,
    ColumnTypeError,
    DimensionError,
    FileLockedError,
    FileReadOnlyError,
    InvalidFileError,
    MergeConflictWarning,
    PyhandlexlError,
    SchemaRebuiltWarning,
    SheetKindError,
    SheetNameError,
    SheetNotFoundError,
    TableExistsError,
    TableNotFoundError,
)
from pyhandlexl.style import TableStyle
from pyhandlexl.table import Table, TableData, TableInfo
from pyhandlexl.validate import (
    check_cell_value,
    check_dimensions,
    check_sheet_name,
    is_valid_xlsx,
)

__version__ = "0.9.5"

__all__ = [
    "CellTypeError",
    "ColumnType",
    "ColumnTypeError",
    "DimensionError",
    "FileLockedError",
    "FileReadOnlyError",
    "InvalidFileError",
    "MergeConflictWarning",
    "MergeReport",
    "PyhandlexlError",
    "SchemaRebuiltWarning",
    "SheetKindError",
    "SheetNameError",
    "SheetNotFoundError",
    "Table",
    "TableData",
    "TableExistsError",
    "TableInfo",
    "TableNotFoundError",
    "TableStyle",
    "append_rows",
    "check_cell_value",
    "check_dimensions",
    "check_sheet_name",
    "clear_all_sheet_data",
    "create_csv",
    "create_sheet",
    "create_workbook",
    "delete_sheet",
    "delete_table",
    "delete_workbook",
    "export_xl_to_csv",
    "grid",
    "import_csv_to_xl",
    "is_valid_xlsx",
    "list_sheets",
    "list_tables",
    "read_sheet",
    "rename_sheet",
    "sheet_exists",
    "sheet_kind",
    "table_info",
    "write_sheet",
]
